<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputKeterangan</name>
   <tag></tag>
   <elementGuidId>9f75c711-605e-4b65-a05f-a71a7dbb2566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[3]/div[6]/div/div/div[2]/div/div/form[1]/div[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[3]/div[6]/div/div/div[2]/div/div/form[1]/div[2]/textarea</value>
      <webElementGuid>7730618d-b267-404c-b95c-2c7a78fb59c4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
