<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opsiPersetujuan</name>
   <tag></tag>
   <elementGuidId>f8554b5a-0c28-4659-81f0-1ff7bbe3a373</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[3]/div[4]/div/div/div[2]/div/div/form/div[0]/select/option[0]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[3]/div[4]/div/div/div[2]/div/div/form/div[0]/select/option[0]</value>
      <webElementGuid>ac84023c-f4fd-4542-a8a3-b7b127a4116f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
