<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Import Excel</name>
   <tag></tag>
   <elementGuidId>5083c159-ad5f-483b-92b4-89444e444775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnImportCMS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnImportCMS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fafd7de-f077-4dc0-b9e6-01b10d2de966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>383d7b63-e5fc-4774-bc71-ba514b0ef188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>702af4b0-1fc9-4fac-aa9b-01af26574e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnImportCMS</value>
      <webElementGuid>ea4cd54a-9cce-4f3c-923e-348320ff2550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Import Excel</value>
      <webElementGuid>fab9188a-6355-4aab-a3e1-6bf7296ff283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnImportCMS&quot;)</value>
      <webElementGuid>f1317a6e-3cd2-4134-bc3e-4f88e3627240</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnImportCMS']</value>
      <webElementGuid>772c2d9c-9158-4785-a6ba-d05a4d6d0f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='uploadFileForm']/button</value>
      <webElementGuid>a9440a84-5db7-4fad-aa80-b41a03ddf954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Pilih Rekening --'])[2]/following::button[1]</value>
      <webElementGuid>b861f867-c978-414d-9a89-5c03bc2ba60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account No.'])[1]/following::button[1]</value>
      <webElementGuid>eefe0356-9353-434d-90c3-751fd7959654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List CMS'])[1]/preceding::button[1]</value>
      <webElementGuid>293645f7-e594-4fd2-be26-bfc0da96d5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Import Excel']/parent::*</value>
      <webElementGuid>95cf2484-2724-4859-8c5b-9beb8355f8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fd5b4158-c650-4e84-9584-8c59eb25e095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnImportCMS' and (text() = 'Import Excel' or . = 'Import Excel')]</value>
      <webElementGuid>802c2a2b-f8ef-4002-865a-405fe62a6aeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
