<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdownBranch</name>
   <tag></tag>
   <elementGuidId>4a676662-4dcd-4a6b-96e8-9b28cdd479ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[normalize-space()='Branch']/following::span[contains(@class,'select2-selection')][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[normalize-space()='Branch']/following::span[contains(@class,'select2-selection')][1]</value>
      <webElementGuid>087c7080-5944-4de6-aeea-5fccd55a58b0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
