<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Import CMS</name>
   <tag></tag>
   <elementGuidId>a8089094-7ec2-4584-b61b-b86dac662ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#import-cms-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='import-cms-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac0136b6-3bdd-4d85-901f-ec79bf65f87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>3b8109ce-8366-403b-a67d-fa4b2c9b62e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>import-cms-tab</value>
      <webElementGuid>185cfb41-6a21-4551-b28a-0a9bc3a34d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b7774a19-2bcb-4c31-b3ec-7fefd2ffc9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#import-cms</value>
      <webElementGuid>bb0b153f-d68a-4367-b140-7a79a56c660b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b10082f3-444a-4bee-a971-d9eb498016ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>import-cms</value>
      <webElementGuid>36031ac8-c1f1-4083-a394-50a6c3e54fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eddc5ab6-1346-4ea7-92d9-786c8ffecdc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Import CMS</value>
      <webElementGuid>e29bd934-543b-4575-a850-d05ee84b72c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;import-cms-tab&quot;)</value>
      <webElementGuid>28952102-7c09-4fd1-8c61-de1e5bdd1783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='import-cms-tab']</value>
      <webElementGuid>636c524b-a1d2-4fa1-9329-7ab0c83d25a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li/a</value>
      <webElementGuid>680c75e9-f9fc-405f-9c33-26f1771d53ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Import CMS')]</value>
      <webElementGuid>a0fc9d85-6d9a-4c9a-8457-bb2094a71c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Cash Management System'])[1]/following::a[1]</value>
      <webElementGuid>336d4aa0-d8c1-4e8d-80b9-e1ce7be86e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKUA KPP'])[4]/following::a[1]</value>
      <webElementGuid>9c0f5b97-5ccb-4307-add6-93094f34cc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Excel'])[1]/preceding::a[1]</value>
      <webElementGuid>51be6c39-6d5a-40b9-84e0-a12ecd6cf9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/preceding::a[2]</value>
      <webElementGuid>4da768bb-642f-4259-9353-6b1098b82bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Import CMS']/parent::*</value>
      <webElementGuid>ad4062e8-5875-4f8f-95e6-226b5053e975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#import-cms')]</value>
      <webElementGuid>5703215e-9771-4acc-8993-6e9a2759a374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a</value>
      <webElementGuid>4c0fe64b-8075-455d-82dc-209e818256d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'import-cms-tab' and @href = '#import-cms' and (text() = 'Import CMS' or . = 'Import CMS')]</value>
      <webElementGuid>9921461d-7aee-4a58-8d71-5abb7c4ca9f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
