<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action Download</name>
   <tag></tag>
   <elementGuidId>b95fcdf8-5bc8-4068-9ae9-05b2326da3ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-primary.btn-download</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f190c00-cf67-4948-8733-944d407a8ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f8809ca-9fe4-4204-abdd-0e5199acd8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary btn-download</value>
      <webElementGuid>37ae362e-7c02-45d8-a3d7-00948827fc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>8c5b7a42-c9c8-40dd-b247-2d69966ea00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>54e02b53-e420-4354-8e27-31ef1de093ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-download</value>
      <webElementGuid>5ce2abea-8c3e-41a8-96aa-56d1ac186521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refidcms</name>
      <type>Main</type>
      <value>eyJpdiI6InVSdlFLMHh1Zmkvc1A4YXVIMUdFRGc9PSIsInZhbHVlIjoiUDFMenE4RnRFckc3VzNham41WEpFZz09IiwibWFjIjoiNzhkMTg2M2NiOWM1ZGZmYWY2ZjcwZTk5N2ExYTVkNTE2MDBlMjk5ZmRhYWUxZDk1MmQzMWJhMDczMzU3Njc3MSIsInRhZyI6IiJ9</value>
      <webElementGuid>23c53840-79c0-4563-aeaa-7922ec47ae1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableImportCms&quot;)/tbody[1]/tr[@class=&quot;cell-padding even&quot;]/td[1]/div[@class=&quot;d-flex justify-content-between align-items-center px-2&quot;]/button[@class=&quot;btn btn-sm btn-primary btn-download&quot;]</value>
      <webElementGuid>ab0f4d5b-da80-4b60-887b-1c919723d0fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>2dfb6eae-b083-401b-b142-afe60636de02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableImportCms']/tbody/tr[8]/td/div/button</value>
      <webElementGuid>2b4883b2-2dc0-4e0a-9c87-265c9e4d1b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REXY'])[4]/following::button[1]</value>
      <webElementGuid>b40ad602-9865-4d4e-9e4d-ce6b37f6d10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KPRS KCU JANUARI 26 (2).xls'])[1]/following::button[1]</value>
      <webElementGuid>23caee86-6d17-4cf6-baa9-de1ea6c7b6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[1]/preceding::button[1]</value>
      <webElementGuid>71c181d1-adbf-41fc-bc87-14d5efe827ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KPRS KCU JANUARI 26.xls'])[1]/preceding::button[1]</value>
      <webElementGuid>4b7f4297-fa68-4401-938a-067e3b00e09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>bfcd57a4-8b18-4ca3-bc5e-4bb035e8c546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Download']</value>
      <webElementGuid>2c547b29-af19-448b-8201-df6c0b8fd746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
