<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Compare Transaction</name>
   <tag></tag>
   <elementGuidId>2f5502f3-7400-4fb0-9b44-fb33217542cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#compare-trx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='compare-trx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3179b3ac-6f89-464f-bca7-f4e0e01b7269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20fa971e-2a86-402a-bde4-c14810700244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>bd835320-69f2-4680-9632-59c658be27a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>compare-trx</value>
      <webElementGuid>9ea4427b-1b59-4137-8c70-861964bc0c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare Transaction</value>
      <webElementGuid>538a541a-9f09-4d9a-b5a3-9c5fbb13344c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;compare-trx&quot;)</value>
      <webElementGuid>ee1876cd-b037-41fc-b782-620eadf57ae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='compare-trx']</value>
      <webElementGuid>bdf9be3b-f094-493c-9ff4-2e3c10514a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/section/div[2]/div/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>36528708-13d2-4fd9-9c18-a42e3e042414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[4]/following::button[1]</value>
      <webElementGuid>c38393e1-0d30-425f-88bf-d1cc245b138f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[8]/following::button[1]</value>
      <webElementGuid>300951e9-1bef-4708-8122-138593adafb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Data Invalid'])[1]/preceding::button[1]</value>
      <webElementGuid>a8c02f80-7759-4379-9f54-442feeb013c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compare Transaction']/parent::*</value>
      <webElementGuid>eafe64f6-fa41-4350-8dc8-d6552f707909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e5594b1d-d5d0-4bef-aca6-eabe1b4baaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'compare-trx' and (text() = 'Compare Transaction' or . = 'Compare Transaction')]</value>
      <webElementGuid>37526dbb-1e3d-48c8-a863-5b58726027de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
