<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown Status for Download</name>
   <tag></tag>
   <elementGuidId>bbfc28dc-c562-4c43-90f7-cf18448191b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status-download</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='status-download']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>36a0437c-7ef1-429f-9a88-2115bdebd7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>77d81457-0e60-44b7-9149-10b5eabb3ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status-download</value>
      <webElementGuid>4ee884c1-2c7f-46f5-8423-3d3462f448ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>0fe33ff1-cee3-491e-ba11-ee6a5679aa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Gagal
                                        Berhasil
                                    </value>
      <webElementGuid>49400f89-6442-4cea-89b6-43cdc089e76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status-download&quot;)</value>
      <webElementGuid>fd1cebea-0dc5-4427-8b42-e6d17c4130cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='status-download']</value>
      <webElementGuid>bf2193c0-a156-4e39-a0b3-1f38d0053a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirmation-wrapper']/table/tbody/tr[3]/td[3]/select</value>
      <webElementGuid>78ed21a4-965b-468d-8524-cf312c9d61c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/following::select[1]</value>
      <webElementGuid>2dcf48cd-331c-4244-9f8d-735e42159f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Transaksi Pembukuan'])[1]/following::select[1]</value>
      <webElementGuid>cf00386a-0798-46ec-8e37-0d3c16d487ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/select</value>
      <webElementGuid>4453245a-b6fc-4f3d-90f9-e7449df92f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'status-download' and @name = 'status' and (text() = '
                                        Gagal
                                        Berhasil
                                    ' or . = '
                                        Gagal
                                        Berhasil
                                    ')]</value>
      <webElementGuid>4b82cc15-ae80-4b61-b7d2-8b78f08a04f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
