<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cmsName</name>
   <tag></tag>
   <elementGuidId>16f2ec14-6266-43dd-811e-c0bef7f6d1ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cmsName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cmsName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88d82c90-187a-4a64-aaff-ce8fcaf3cafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ae9ef37-73f8-408d-a2f7-1ab68ff96914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a5699cc7-ea3e-4756-b7cb-34fa4408160e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmsName</value>
      <webElementGuid>e547e8b7-d0b5-46a0-a7fa-81f38565d853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmsName</value>
      <webElementGuid>a7c459b3-809e-4c9c-aa05-a52714288467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama CMS</value>
      <webElementGuid>5ebd51b3-07b9-412f-8903-43bdf1d4f2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmsName&quot;)</value>
      <webElementGuid>8ddfb41b-c65f-4f2c-b846-4e1894db56ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cmsName']</value>
      <webElementGuid>9de92e94-1c8e-4404-b2f5-cbe4ba356531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='uploadFileForm']/div[2]/div/input</value>
      <webElementGuid>d5c45ec1-af44-4df0-83d5-cb67f8ab9563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ea8e7038-e592-46f5-a30d-a304b1dc8fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cmsName' and @id = 'cmsName' and @placeholder = 'Masukkan Nama CMS']</value>
      <webElementGuid>c6f09c7e-d0df-45f8-acf2-06f96154f40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
