<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_CompareTransaction</name>
   <tag></tag>
   <elementGuidId>982088c2-100f-497c-b053-863528ba92c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='compare-trx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='compare-trx']</value>
      <webElementGuid>278de34f-364a-4e42-af01-e09f12018436</webElementGuid>
   </webElementProperties>
</WebElementEntity>
