<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPersentase</name>
   <tag></tag>
   <elementGuidId>753f6a89-fed7-4dd5-b72f-0aa60e4012e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='PersentaseJaminan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='PersentaseJaminan']</value>
      <webElementGuid>cf952e8a-50b6-4e70-bb4a-37cdce6615f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
