<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputTGLAwalBG</name>
   <tag></tag>
   <elementGuidId>ab9199f2-dede-4dea-9f05-994625f27d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='TglAwalJangkaWaktuBG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='TglAwalJangkaWaktuBG']</value>
      <webElementGuid>b9846524-cf8e-4905-acd4-1759abcf6560</webElementGuid>
   </webElementProperties>
</WebElementEntity>
