<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputSubmission</name>
   <tag></tag>
   <elementGuidId>2c71b744-3790-4169-8a74-a0105d2894bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='SubmissionNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='SubmissionNumber']</value>
      <webElementGuid>94928127-6441-42b3-9759-b33cf05467c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
