<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSignIn</name>
   <tag></tag>
   <elementGuidId>22ff0ca4-5382-404e-b0aa-ab36e227d7b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-tb-test-id='tabbed-auth-dialog-test-id-Dialog-Content']//button[@data-tb-test-id='auth-component-sign-in-button-Button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-tb-test-id='tabbed-auth-dialog-test-id-Dialog-Content']//button[@data-tb-test-id='auth-component-sign-in-button-Button']</value>
      <webElementGuid>257bd910-8d86-4e39-b818-cd6d6fcd6c30</webElementGuid>
   </webElementProperties>
</WebElementEntity>
