<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dataDevelopment</name>
   <tag></tag>
   <elementGuidId>d511fe7a-2a9b-4aba-9f4a-18079a381988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title='Development']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='Development']</value>
      <webElementGuid>de00f554-e0bd-4cbb-99d2-d936d069aebf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
