<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorMessage</name>
   <tag></tag>
   <elementGuidId>217a4d9a-6c48-45af-a011-9acf27b4ae18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-tb-test-id='relational-dialog-error-section-error-details-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-tb-test-id='relational-dialog-error-section-error-details-header']</value>
      <webElementGuid>17878de5-2cdb-40bd-819d-725a17192f1e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
