<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPassword</name>
   <tag></tag>
   <elementGuidId>6f8824ab-fccc-414e-be32-0086e03f482d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-tb-test-id='tabbed-auth-dialog-test-id-Dialog-Content']//input[@data-tb-test-id='auth-component-password-text-field-TextInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-tb-test-id='tabbed-auth-dialog-test-id-Dialog-Content']//input[@data-tb-test-id='auth-component-password-text-field-TextInput']</value>
      <webElementGuid>8fb7e08d-6ad0-4bc0-9282-8f7301f6a2b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
