<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPassword</name>
   <tag></tag>
   <elementGuidId>6f8824ab-fccc-414e-be32-0086e03f482d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@data-tb-test-id='auth-component-password-text-field-TextInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@data-tb-test-id='auth-component-password-text-field-TextInput']</value>
      <webElementGuid>10c96498-0329-4719-b260-04f9e93206d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
