<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>boxCapta</name>
   <tag></tag>
   <elementGuidId>1bc2e54b-ee9a-4f84-921d-2364674b7155</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label//input[@type='checkbox']</value>
      <webElementGuid>34cc5368-ba62-4088-a2d2-303dcbbbcf51</webElementGuid>
   </webElementProperties>
</WebElementEntity>
